// CODE GENERATED BY plant

package main

import (
	"log"
)

import (
	"automatica.team/plant"
)

import (
	"demo/mods/private"
)

func main() {
	// Create a plant
	p, err := plant.New("plant.yml")
	if err != nil {
		log.Fatal(err)
	}

	// Dependencies

	// Modules
	p.Add(private.New())

	// Build a configured bot
	b, err := p.Build()
	if err != nil {
		log.Fatal(err)
	}

	// Start the built bot
	b.Start()
}
