package template

import "text/template"

var Run = template.Must(
	template.New("Run").Funcs(funcs).Parse(run),
)

const run = `// CODE GENERATED BY plant; DO NOT EDIT!
package main

import (
	"log"
)

// Import plant modules
import (
	"automatica.team/plant"
	{{- range .Mods }}
	"automatica.team/{{ importmods .Name }}"
	{{ end }}
)

// Import plant dependencies
import (
	{{- range .Deps }}
	_ "automatica.team/{{ importdeps .Name }}"
	{{ end }}
)

func main() {
	// Create a plant
	p, err := plant.New("plant.yml")
	if err != nil {
		log.Fatal(err)
	}

	// Connect to deps
	d, err := p.Connect()
	if err != nil {
		log.Fatal(err)
	}

	// Compose a new bot
	b, err := p.Compose()
	if err != nil {
		log.Fatal(err)
	}

	// Add modules to the bot
	{{- range .Mods }}
	p.Add({{ modname .Name }}.New(b, d))
	{{ end }}

	// Build the bot
	if err := p.Build(b); err != nil {
		log.Fatal(err)
	}

	// Start the bot
	b.Start()
}
`
