package template

import "text/template"

var Run = template.Must(
	template.New("Run").Funcs(funcs).Parse(run),
)

const run = `// CODE GENERATED BY plant
package main

import (
	"log"
)

import (
	"automatica.team/plant"
	{{- range .Mods }}
	"automatica.team/{{ import .Name "mods" }}"
	{{- end }}
	{{- range .Deps }}
	"automatica.team/{{ import .Name "deps" }}"
	{{- end }}
)

func main() {
	// Create a plant
	p, err := plant.New("plant.yml")
	if err != nil {
		log.Fatal(err)
	}

	// Dependencies
	{{- range .Deps }}
	p.Inject({{ basename .Name }}.New())
	{{- end }}

	// Modules
	{{- range .Mods }}
	p.Add({{ basename .Name }}.New())
	{{- end }}

	// Build a configured bot
	b, err := p.Build()
	if err != nil {
		log.Fatal(err)
	}

	// Start the built bot
	b.Start()
}
`
